export interface Service {
  slug: string;
  title: string;
  shortTitle: string;
  category: "commercial" | "medical" | "industrial" | "additional";
  description: string;
  longDescription: string;
  image: string;
  features: string[];
  benefits: string[];
}

export const services: Service[] = [
  // Commercial
  {
    slug: "banks",
    title: "Bank Cleaning Services",
    shortTitle: "Banks",
    category: "commercial",
    description: "Professional cleaning for banking facilities with strict security protocols.",
    longDescription: "Our banking facility cleaning services maintain pristine environments in lobbies, teller areas, offices, ATM areas, and vaults. We follow strict security protocols and work within your schedule to minimize disruption to operations.",
    image: "/images/services/4a7ffe20-cb17-4d46-9434-76a526c68257_1767643062610-sMYPZHkq.jpg",
    features: ["Lobby and teller area maintenance", "ATM and kiosk cleaning", "Vault area cleaning", "Security-compliant protocols", "After-hours service available", "Customer-facing area detailing"],
    benefits: ["Enhanced customer experience", "Security-compliant cleaning", "Flexible scheduling around operations", "Consistent pristine presentation"],
  },
  {
    slug: "car-dealerships",
    title: "Car Dealership Cleaning Services",
    shortTitle: "Car Dealerships",
    category: "commercial",
    description: "Showroom-quality cleaning for automotive dealerships.",
    longDescription: "Keep your showroom floors gleaming and service bays spotless. Our dealership cleaning covers showrooms, service departments, customer lounges, offices, and exterior areas to maintain that premium buying experience.",
    image: "/images/services/15bb683b-a628-463a-842b-4e61212a5dc2_1767643055559-DLNZ6rtn.jpg",
    features: ["Showroom floor maintenance", "Service bay degreasing", "Customer lounge cleaning", "Window and glass detailing", "Exterior pressure washing", "Parts department organization"],
    benefits: ["Premium showroom presentation", "Improved customer confidence", "Enhanced buying environment", "Automotive showroom and service area cleaning"],
  },
  {
    slug: "churches",
    title: "Church Cleaning Services",
    shortTitle: "Churches",
    category: "commercial",
    description: "Reverent, thorough cleaning for houses of worship.",
    longDescription: "We provide respectful, thorough cleaning services for churches and religious facilities. From sanctuaries and fellowship halls to classrooms and nurseries, we ensure every space is welcoming for your congregation.",
    image: "/images/services/f7990ebd-7762-4961-bb15-60648046f3b4_1767643158635-DqH5-qtO.jpg",
    features: ["Sanctuary and altar care", "Fellowship hall cleaning", "Nursery sanitization", "Classroom maintenance", "Restroom deep cleaning", "Event setup and teardown support"],
    benefits: ["Welcoming worship environment", "Sanitized nursery areas", "Ready for events and services", "Respectful care of sacred spaces"],
  },
  {
    slug: "multi-tenant-offices",
    title: "Multi-Tenant Office Cleaning",
    shortTitle: "Office Buildings",
    category: "commercial",
    description: "Comprehensive cleaning for multi-tenant commercial office buildings.",
    longDescription: "Managing cleaning for multi-tenant office buildings requires coordination, consistency, and professionalism. We handle common areas, individual suites, restrooms, lobbies, and parking structures with customized schedules for each tenant.",
    image: "/images/services/13861450-daa5-4248-bb08-de14e018fd16_1767643162967-C7NIC8Ex.jpg",
    features: ["Common area maintenance", "Individual suite cleaning", "Lobby and elevator care", "Restroom servicing", "Parking structure cleaning", "Administrative office cleaning"],
    benefits: ["Consistent quality across all tenants", "Flexible scheduling per tenant", "Single point of contact for building management", "Professional appearance maintained"],
  },
  {
    slug: "restaurants",
    title: "Restaurant Cleaning Services",
    shortTitle: "Restaurants",
    category: "commercial",
    description: "Health code compliant deep cleaning for food service facilities.",
    longDescription: "Our restaurant cleaning services go beyond surface cleaning to ensure full health code compliance. We handle kitchen deep cleaning, dining area maintenance, restroom sanitization, and grease trap management for restaurants and food service franchises.",
    image: "/images/services/d865150d-7215-4494-bbdf-06ccbe397679_1767643388358-BGdRjNKS.jpg",
    features: ["Kitchen deep cleaning", "Hood and grease trap service", "Dining area maintenance", "Restroom sanitization", "Food prep area sterilization", "Health code compliance cleaning"],
    benefits: ["Health inspection ready", "Safe food preparation environment", "Enhanced dining experience", "Food service industry cleaning protocols"],
  },
  {
    slug: "retail-facilities",
    title: "Retail Facility Cleaning",
    shortTitle: "Retail",
    category: "commercial",
    description: "Professional cleaning for retail stores and shopping centers.",
    longDescription: "Create an inviting shopping experience with our retail facility cleaning services. We maintain storefronts, sales floors, fitting rooms, storage areas, and common spaces in retail environments of all sizes.",
    image: "/images/services/ab8693e4-5b4d-401a-8dd4-0940e4b26366_1767643390203-3vwITDI4.jpg",
    features: ["Sales floor maintenance", "Fitting room sanitization", "Display and shelf cleaning", "Entrance and storefront care", "Stockroom organization", "Customer service area maintenance"],
    benefits: ["Inviting shopping environment", "Clean fitting rooms boost sales", "Professional storefront appearance", "Appliance store flooring"],
  },
  {
    slug: "schools",
    title: "School & University Cleaning",
    shortTitle: "Schools",
    category: "commercial",
    description: "Safe, thorough cleaning for educational institutions.",
    longDescription: "Our educational facility cleaning services create healthy learning environments. From classrooms and laboratories to gymnasiums and cafeterias, we use EPA-approved products safe for students and staff at schools and universities.",
    image: "/images/services/46d54f10-ed35-44a7-89ce-19eb8f9ebbfb_1767643425721-BVQrG0Tg.jpg",
    features: ["Classroom sanitization", "Cafeteria deep cleaning", "Gymnasium maintenance", "Laboratory cleaning", "Restroom servicing", "Athletic facility cleaning and sanitization"],
    benefits: ["Healthy learning environment", "EPA-approved safe products", "Reduced student illness", "Athletic equipment storage cleaning"],
  },
  {
    slug: "gymnasiums",
    title: "Gymnasium Cleaning Services",
    shortTitle: "Gymnasiums",
    category: "commercial",
    description: "Specialized cleaning for fitness and athletic facilities.",
    longDescription: "Gyms and fitness centers require specialized cleaning to prevent the spread of bacteria and maintain equipment. Our gymnasium cleaning includes equipment sanitization, locker rooms, showers, pool areas, and athletic training facilities.",
    image: "/images/services/a9826249-9689-4a7d-bfd2-9675ebac083a_1767643428382-B6DbbN7F.jpg",
    features: ["Equipment sanitization", "Locker room deep cleaning", "Shower and pool area maintenance", "Floor mat cleaning", "Mirror and glass care", "Athletic training facilities"],
    benefits: ["Reduced infection risk", "Equipment longevity", "Member satisfaction", "Athletic Support Facilities"],
  },
  // Medical
  {
    slug: "clinics",
    title: "Clinic & Private Practice Cleaning",
    shortTitle: "Clinics",
    category: "medical",
    description: "Medical-grade cleaning for clinics and private practices.",
    longDescription: "Our clinical cleaning services meet the highest healthcare standards. We provide thorough sanitization of exam rooms, waiting areas, and medical offices using EPA-registered hospital-grade disinfectants and follow strict infection control protocols.",
    image: "/images/services/10058993-6a9c-45d5-b3a5-d8635899bae7_1767644062493-BSaFDC1I.jpg",
    features: ["Exam room terminal cleaning", "Waiting area sanitization", "Medical waste area management", "EPA-registered disinfectants", "HIPAA-compliant practices", "ATP testing verification"],
    benefits: ["Infection control compliance", "Patient confidence", "Regulatory readiness", "ATP Testing Verification"],
  },
  {
    slug: "surgery-centers",
    title: "Surgery Center Cleaning",
    shortTitle: "Surgery Centers",
    category: "medical",
    description: "Sterile environment maintenance for ambulatory surgical centers.",
    longDescription: "Ambulatory surgical centers demand the highest levels of cleanliness. Our certified teams perform terminal cleaning of operating rooms, pre-op and recovery areas, and sterilization departments following AORN and Joint Commission guidelines.",
    image: "/images/services/338a6f3d-4f6d-49dc-9e4b-0043852bf68c_1767644054741-BZeABH9x.jpg",
    features: ["Operating room terminal cleaning", "Pre-op and PACU cleaning", "Sterile processing area maintenance", "AORN guideline compliance", "ATP testing and documentation for compliance", "Air filtration system cleaning"],
    benefits: ["Surgical site infection prevention", "Accreditation compliance", "Complete facility sanitization services", "Alignment with accreditation standards for healthcare organizations"],
  },
  {
    slug: "imaging-facilities",
    title: "Imaging Facility Cleaning",
    shortTitle: "Imaging Centers",
    category: "medical",
    description: "Specialized cleaning for diagnostic imaging and radiology facilities.",
    longDescription: "Imaging facilities house sensitive, expensive equipment that requires careful cleaning protocols. Our trained teams understand the unique needs of MRI suites, CT rooms, X-ray areas, and ultrasound rooms.",
    image: "/images/services/10058993-6a9c-45d5-b3a5-d8635899bae7_1767644062493-BSaFDC1I.jpg",
    features: ["MRI suite cleaning protocols", "CT room maintenance", "Patient prep area sanitization", "Equipment-safe cleaning products", "Emergency imaging services", "Radiation safety compliance"],
    benefits: ["Equipment protection", "Patient safety", "Regulatory compliance", "Emergency imaging services"],
  },
  {
    slug: "laboratories",
    title: "Laboratory Cleaning Services",
    shortTitle: "Laboratories",
    category: "medical",
    description: "Contamination-controlled cleaning for laboratory environments.",
    longDescription: "Laboratory environments require meticulous cleaning to prevent cross-contamination and maintain controlled conditions. Our lab cleaning teams are trained in biosafety protocols, chemical handling, and cleanroom maintenance procedures.",
    image: "/images/services/338a6f3d-4f6d-49dc-9e4b-0043852bf68c_1767644054741-BZeABH9x.jpg",
    features: ["Biosafety cabinet cleaning", "Fume hood maintenance", "Controlled environment protocols", "Chemical spill response", "Cleanroom-rated procedures", "Air purification during and after cleaning"],
    benefits: ["Cross-contamination prevention", "Regulatory compliance", "Research integrity", "Airborne pathogen capture"],
  },
  {
    slug: "sports-rehabilitation",
    title: "Sports Rehabilitation Facility Cleaning",
    shortTitle: "Sports Rehab",
    category: "medical",
    description: "Hygienic cleaning for sports medicine and rehabilitation centers.",
    longDescription: "Sports rehabilitation facilities require frequent sanitization of treatment tables, hydrotherapy pools, exercise equipment, and patient care areas. Our teams maintain the highest hygiene standards to protect recovering athletes.",
    image: "/images/services/a9826249-9689-4a7d-bfd2-9675ebac083a_1767643428382-B6DbbN7F.jpg",
    features: ["Treatment room sanitization", "Hydrotherapy pool maintenance", "Equipment cleaning", "Locker room servicing", "Physical therapy area care", "Athletic training facilities"],
    benefits: ["Infection prevention", "Patient safety", "Equipment longevity", "Athletic Support Facilities"],
  },
  {
    slug: "terminal-sanitization",
    title: "Terminal Sanitization Services",
    shortTitle: "Terminal Cleaning",
    category: "medical",
    description: "Complete terminal cleaning and disinfection for healthcare environments.",
    longDescription: "Our terminal sanitization services provide the deepest level of healthcare cleaning. Using UV-C technology, electrostatic spraying, and EPA-registered hospital-grade disinfectants, we eliminate pathogens from patient rooms, ORs, and critical care areas.",
    image: "/images/services/338a6f3d-4f6d-49dc-9e4b-0043852bf68c_1767644054741-BZeABH9x.jpg",
    features: ["UV-C disinfection technology", "Electrostatic spraying", "Hospital-grade disinfectants", "ATP testing results", "Complete room turnover", "Air filtration system maintenance"],
    benefits: ["Healthcare-associated infection reduction", "Accreditation support", "Documented disinfection verification", "Advanced Sanitization Technology"],
  },
  // Industrial
  {
    slug: "factory-plants",
    title: "Factory & Plant Cleaning Services",
    shortTitle: "Factories",
    category: "industrial",
    description: "Heavy-duty industrial cleaning for manufacturing facilities.",
    longDescription: "Our industrial cleaning teams handle the toughest environments. From production floors and assembly lines to warehouses and loading docks, we have the equipment and expertise to keep manufacturing facilities clean, safe, and OSHA-compliant.",
    image: "/images/services/d865150d-7215-4494-bbdf-06ccbe397679_1767643388358-BGdRjNKS.jpg",
    features: ["Production floor cleaning", "Assembly line maintenance", "Heavy equipment degreasing", "Loading dock pressure washing", "OSHA compliance cleaning", "Air filtration system cleaning"],
    benefits: ["Workplace safety improvement", "OSHA compliance", "Equipment longevity", "Asset preservation programs"],
  },
  {
    slug: "warehouses",
    title: "Warehouse Cleaning Services",
    shortTitle: "Warehouses",
    category: "industrial",
    description: "Large-scale cleaning solutions for warehouse and distribution centers.",
    longDescription: "Large warehouse and distribution center cleaning requires industrial-grade equipment and experienced crews. We handle aisle and floor maintenance, rack cleaning, dock areas, and office spaces within warehouse facilities.",
    image: "/images/services/46d54f10-ed35-44a7-89ce-19eb8f9ebbfb_1767643425721-BVQrG0Tg.jpg",
    features: ["Aisle and floor maintenance", "Rack and shelving cleaning", "Dock area maintenance", "Office space cleaning", "Restroom servicing", "Concrete floor scrubbing"],
    benefits: ["Safety compliance", "Organized workspace", "Dust and debris control", "Aisle and floor maintenance"],
  },
  {
    slug: "petrochemical-plants",
    title: "Petrochemical Plant Cleaning",
    shortTitle: "Petrochemical",
    category: "industrial",
    description: "Safety-focused cleaning for petrochemical and chemical processing facilities.",
    longDescription: "Petrochemical facility cleaning requires specialized knowledge of hazardous materials, safety protocols, and industrial cleaning techniques. Our HAZWOPER-certified teams handle control rooms, administrative areas, and decontamination zones.",
    image: "/images/services/f7990ebd-7762-4961-bb15-60648046f3b4_1767643158635-DqH5-qtO.jpg",
    features: ["Control room cleaning", "Administrative area maintenance", "Decontamination zone protocols", "HAZWOPER-certified personnel", "Chemical-safe cleaning products", "Air filtration system cleaning"],
    benefits: ["Safety compliance", "Hazardous material handling", "Regulatory documentation", "All safety standards met"],
  },
  {
    slug: "hydroelectric-plants",
    title: "Hydroelectric Plant Cleaning",
    shortTitle: "Hydroelectric",
    category: "industrial",
    description: "Specialized cleaning services for power generation facilities.",
    longDescription: "Our hydroelectric and power plant cleaning services maintain both the operational and administrative areas of power generation facilities. We understand the unique safety requirements and access protocols of energy infrastructure.",
    image: "/images/services/13861450-daa5-4248-bb08-de14e018fd16_1767643162967-C7NIC8Ex.jpg",
    features: ["Control room maintenance", "Administrative office cleaning", "Visitor center care", "Safety-compliant protocols", "High-security area access", "Turbine hall cleaning"],
    benefits: ["Regulatory compliance", "Safety-first approach", "Critical infrastructure cleanliness", "All safety standards met"],
  },
  // Additional Services
  {
    slug: "concrete-floors",
    title: "Concrete Floor Cleaning Services",
    shortTitle: "Concrete Floors",
    category: "additional",
    description: "Professional concrete floor cleaning, polishing, and coating services.",
    longDescription: "Our concrete floor services include industrial-grade cleaning, diamond polishing, epoxy coating, and antimicrobial urethane cement applications. We restore and protect concrete floors in commercial, medical, and industrial environments.",
    image: "/images/services/d865150d-7215-4494-bbdf-06ccbe397679_1767643388358-BGdRjNKS.jpg",
    features: ["Diamond grinding and polishing", "Epoxy coating systems", "Antimicrobial urethane cement with cove base integration", "Stain removal", "Slip resistance treatment", "Advanced Coating Systems"],
    benefits: ["Extended floor lifespan", "ADA slip resistance compliant", "Aesthetic appeal", "Aesthetics"],
  },
  {
    slug: "post-construction",
    title: "Post-Construction Cleanup",
    shortTitle: "Post-Construction",
    category: "additional",
    description: "Comprehensive cleanup services after construction and renovation projects.",
    longDescription: "Our post-construction cleaning teams handle the complete cleanup after construction and renovation projects. From debris removal and dust elimination to final detail cleaning, we get your space move-in ready.",
    image: "/images/services/4a7ffe20-cb17-4d46-9434-76a526c68257_1767643062610-sMYPZHkq.jpg",
    features: ["Debris removal", "Construction dust elimination", "Window and glass cleaning", "Floor scrubbing and sealing", "HVAC vent cleaning", "Final detail cleaning"],
    benefits: ["Move-in ready spaces", "Dust-free environment", "Professional finish", "Comprehensive cleanup services after construction and renovation projects"],
  },
  {
    slug: "industrial-cleanup",
    title: "Industrial Cleanup Services",
    shortTitle: "Industrial Cleanup",
    category: "additional",
    description: "Emergency and scheduled industrial cleanup services.",
    longDescription: "Our industrial cleanup teams respond to both emergency situations and scheduled deep cleaning needs. We handle chemical spills, accident sites, equipment decontamination, and facility restoration with certified response teams.",
    image: "/images/services/f7990ebd-7762-4961-bb15-60648046f3b4_1767643158635-DqH5-qtO.jpg",
    features: ["Chemical spill response", "Accident site cleaning", "Equipment decontamination", "Facility restoration", "Certified Response Teams", "Emergency response available 24/7"],
    benefits: ["Rapid deployment teams available around the clock", "Certified cleanup procedures", "Regulatory compliance documentation", "Complete restoration services"],
  },
  {
    slug: "power-washing",
    title: "Power Washing Services",
    shortTitle: "Power Washing",
    category: "additional",
    description: "Commercial and industrial pressure washing for exteriors and hard surfaces.",
    longDescription: "Our commercial power washing services restore building exteriors, parking structures, sidewalks, loading docks, and other hard surfaces. We use industrial-grade equipment and environmentally responsible cleaning solutions.",
    image: "/images/services/ab8693e4-5b4d-401a-8dd4-0940e4b26366_1767643390203-3vwITDI4.jpg",
    features: ["Building exterior washing", "Parking structure cleaning", "Sidewalk and entrance cleaning", "Loading dock pressure washing", "Graffiti removal", "Fleet vehicle washing"],
    benefits: ["Curb appeal improvement", "Safety hazard removal", "Property value protection", "Environmental compliance"],
  },
  {
    slug: "windows",
    title: "Window Cleaning Services",
    shortTitle: "Windows",
    category: "additional",
    description: "Professional interior and exterior window cleaning for commercial properties.",
    longDescription: "Crystal-clear windows enhance your building's appearance and let in natural light. Our window cleaning teams handle interior and exterior window cleaning for buildings of all sizes, including architectural glass features and high-rise properties.",
    image: "/images/services/15bb683b-a628-463a-842b-4e61212a5dc2_1767643055559-DLNZ6rtn.jpg",
    features: ["Interior and exterior cleaning", "High-rise window washing", "Architectural glass features", "Screen cleaning and repair", "Hard water stain removal", "Skylight cleaning"],
    benefits: ["Enhanced natural light", "Professional building appearance", "Extended window lifespan", "Improved tenant satisfaction"],
  },
  {
    slug: "upholstery",
    title: "Upholstery Cleaning Services",
    shortTitle: "Upholstery",
    category: "additional",
    description: "Professional upholstery and carpet cleaning for commercial spaces.",
    longDescription: "Our upholstery and carpet cleaning services extend the life of your furnishings and improve indoor air quality. We use hot water extraction, dry cleaning, and specialized treatments for all types of commercial fabrics and carpeting.",
    image: "/images/services/a9826249-9689-4a7d-bfd2-9675ebac083a_1767643428382-B6DbbN7F.jpg",
    features: ["Hot water extraction", "Dry cleaning methods", "Stain treatment and removal", "Fabric protection application", "Carpet shampooing", "Odor elimination"],
    benefits: ["Extended furniture lifespan", "Improved indoor air quality", "Professional appearance", "Cost savings vs. replacement"],
  },
  {
    slug: "specialized-cleaning",
    title: "Specialized Cleaning Services",
    shortTitle: "Specialized",
    category: "additional",
    description: "Custom cleaning solutions for unique facility requirements.",
    longDescription: "When standard cleaning isn't enough, our specialized cleaning services deliver custom solutions. From biohazard remediation and crime scene cleanup to data center cleaning and controlled environment maintenance, we handle it all.",
    image: "/images/services/10058993-6a9c-45d5-b3a5-d8635899bae7_1767644062493-BSaFDC1I.jpg",
    features: ["Biohazard remediation", "Controlled environment cleaning", "Data center maintenance", "Disaster restoration", "Advanced Equipment Deployment", "Custom protocol development"],
    benefits: ["Expert handling of sensitive situations", "Certified specialized teams", "Custom solutions for unique needs", "Advanced Equipment Fleet"],
  },
];

export const serviceCategories = [
  {
    id: "commercial",
    name: "Commercial Services",
    description: "Professional cleaning for commercial facilities of all sizes.",
    icon: "Building2",
  },
  {
    id: "medical",
    name: "Medical Services",
    description: "Healthcare-grade sanitization and infection control.",
    icon: "Heart",
  },
  {
    id: "industrial",
    name: "Industrial Services",
    description: "Heavy-duty cleaning for industrial and manufacturing facilities.",
    icon: "Factory",
  },
  {
    id: "additional",
    name: "Additional Services",
    description: "Specialized cleaning and maintenance solutions.",
    icon: "Sparkles",
  },
] as const;

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}

export function getServicesByCategory(category: string): Service[] {
  return services.filter((s) => s.category === category);
}

export function getAllSlugs(): string[] {
  return services.map((s) => s.slug);
}
