apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mgs-ingress
  namespace: mgs-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts: [api.mgssupplyandservices.com]
      secretName: mgs-api-tls
  rules:
    - host: api.mgssupplyandservices.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: mgs-backend, port: { number: 80 } }
