apiVersion: v1
kind: Service
metadata:
  name: {{ include "mgs-app.fullname" . }}-backend
  labels: {{- include "mgs-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  selector: { app: mgs-backend }
